SNTP implementation
drasyl/drasyl pull request #424
Opened 2023-05-12 14:32 UTC by KevinRoebert

See also:
- https://github.com/Free-Software-for-Android/NTPSync
- https://github.com/boundary/wireshark/blob/master/epan/dissectors/packet-ntp.c
- https://datatracker.ietf.org/doc/rfc2030/

2023-07-28 20:32 UTC, HeikoBornholdt requested changes
Ideen wie wir das integrieren? Vermutlich erst einmal nur in den DrasylNode (weil das unser "Rundum-sorglos"-Interface ist)?

2023-07-28 20:32 UTC, HeikoBornholdt commented on drasyl-extras/src/main/java/org/drasyl/handler/sntp/SNTPCodec.java
> +            // read first byte with LE, VN and mode
LI anstelle von LE?

2023-07-28 20:39 UTC, KevinRoebert commented
> Ideen wie wir das integrieren? Vermutlich erst einmal nur in den DrasylNode (weil das unser "Rundum-sorglos"-Interface ist)?

Gute Frage. Hatte ich auch schon überlegt. Wäre vermutlich am einfachsten. Man könnte natürlich auch einen Handler bauen, der dann einen SNTP-Call macht und eine Exception durch die Pipeline feuert wenn die Zeit abweicht. Dann könnte man das überall einfach hinzufügen

2023-07-29 07:56 UTC, HeikoBornholdt approved these changes

2023-07-29 07:59 UTC, HeikoBornholdt commented
> > Ideen wie wir das integrieren? Vermutlich erst einmal nur in den DrasylNode (weil das unser "Rundum-sorglos"-Interface ist)?
> 
> Gute Frage. Hatte ich auch schon überlegt. Wäre vermutlich am einfachsten. Man könnte natürlich auch einen Handler bauen, der dann einen SNTP-Call macht und eine Exception durch die Pipeline feuert wenn die Zeit abweicht. Dann könnte man das überall einfach hinzufügen

Meinst du wir können das in den bestehenden DatagramChannel integrieren? Oder brauchen wir dafür einen dedizierten Channel?

2023-07-29 18:49 UTC, KevinRoebert commented
> > > Ideen wie wir das integrieren? Vermutlich erst einmal nur in den DrasylNode (weil das unser "Rundum-sorglos"-Interface ist)?
> > 
> > 
> > Gute Frage. Hatte ich auch schon überlegt. Wäre vermutlich am einfachsten. Man könnte natürlich auch einen Handler bauen, der dann einen SNTP-Call macht und eine Exception durch die Pipeline feuert wenn die Zeit abweicht. Dann könnte man das überall einfach hinzufügen
> 
> Meinst du wir können das in den [bestehenden DatagramChannel](https://github.com/drasyl/drasyl/blob/master/drasyl-core/src/main/java/org/drasyl/handler/remote/UdpServerChannelInitializer.java) integrieren? Oder brauchen wir dafür einen dedizierten Channel?

Würde vermutlich funktionieren. Es gibt aber für die SNTP Nachrichten keine Magic Number. Die Frage ist halt, was wir davon hätten einen One Time UDP-Client in unseren UDP-Server-Channel zu implementieren.

2023-07-29 20:48 UTC, HeikoBornholdt commented
> > > > Ideen wie wir das integrieren? Vermutlich erst einmal nur in den DrasylNode (weil das unser "Rundum-sorglos"-Interface ist)?
> > > 
> > > 
> > > Gute Frage. Hatte ich auch schon überlegt. Wäre vermutlich am einfachsten. Man könnte natürlich auch einen Handler bauen, der dann einen SNTP-Call macht und eine Exception durch die Pipeline feuert wenn die Zeit abweicht. Dann könnte man das überall einfach hinzufügen
> > 
> > 
> > Meinst du wir können das in den [bestehenden DatagramChannel](https://github.com/drasyl/drasyl/blob/master/drasyl-core/src/main/java/org/drasyl/handler/remote/UdpServerChannelInitializer.java) integrieren? Oder brauchen wir dafür einen dedizierten Channel?
> 
> Würde vermutlich funktionieren. Es gibt aber für die SNTP Nachrichten keine Magic Number. Die Frage ist halt, was wir davon hätten einen One Time UDP-Client in unseren UDP-Server-Channel zu implementieren.

Am Ende müssten wir doch nur einmal beim Start prüfen, ob die Zeit korrekt geht. Oder willst du das periodisch im Hintergrund laufen lassen (1x pro Java-Prozess würde ja reichen) und dann irgendeine Warnung loggen, wenn der Time Offset irgendeinen Grenzwert erreicht?

2023-09-22 15:05 UTC, HeikoBornholdt requested changes

2023-09-22 15:05 UTC, HeikoBornholdt commented on drasyl-node/src/main/java/org/drasyl/node/DrasylNode.java
> +                if (offset > 60_000) {
Ich erhalte hier eine `NullPointerException` weil `offset` gleich `null` ist.

2023-09-22 15:05 UTC, HeikoBornholdt commented on drasyl-extras/src/main/java/org/drasyl/handler/sntp/SNTPClient.java
> +                                result.complete(null);
Ich erhalte hier Zuhause folgende Exception:
```
java.net.PortUnreachableException: readAddress(..) failed: Connection refused
	at io.netty.channel.kqueue.KQueueDatagramChannel$KQueueDatagramChannelUnsafe.readReady(KQueueDatagramChannel.java:399)
	at io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:387)
	at io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:218)
	at io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:296)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection refused
```

`server` ist bei mir Zuhause `192.168.188.1/<unresolved>:123`

Durch diese Exception wird `result` auf `null` gesetzt und ich erhalte die NPE aus dem anderen Kommentar.

2023-09-27 18:51 UTC, KevinRoebert commented
@HeikoBornholdt Should we merge?

2023-10-02 20:58 UTC, HeikoBornholdt requested changes
Checkstyle violations fixen. Ansonsten sieht's gut aus.

2023-10-13 16:52 UTC, merged