Replace ConnectionHandshakeHandler and GoBackNArq handlers with ConnectionHandler
drasyl/drasyl pull request #588
Opened 2024-03-12 00:03 UTC by HeikoBornholdt

…

2024-03-12 19:38 UTC, KevinRoebert requested changes

2024-03-12 19:40 UTC, KevinRoebert commented
Die Tests failen auch :(

2024-03-12 22:16 UTC, HeikoBornholdt commented
> Die Tests failen auch :(

ist noch draft

2024-03-14 20:27 UTC, HeikoBornholdt commented on drasyl-cli/src/main/java/org/drasyl/cli/wormhole/channel/WormholeSendChildChannelInitializer.java
> +        if (false) {
zum debuggen in Wireshark

2024-03-31 00:16 UTC, merged